### PR TITLE
Upgrade project to support VS 2017

### LINKED ISSUE #230: Support BuildBundlerMinifier on Microsoft.NET.Sdk for .NET Core
### Installed product versions
dotnet-cli 1.0.0-rc3-004350

### Description
In MSBuild 15 projects, BundlerBuildTask is imported when the BuildBundlerMinifier  package is referenced, but the task doesn't support .NET Core.

### Steps to recreate
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
      <PackageReference Include="BuildBundlerMinifier" Version="2.2.306" />
   </ItemGroup>
</Project>
```

dotnet restore
dotnet build

### Current behavior
UsingTask fails to load because it isn't compatible with MSBuild 15 and .NET Core.

> C:\Users\namc\.nuget\packages\buildbundlerminifier\2.2.306\build\BuildBundlerMinifier.targets(15,5): error MSB4062: The "BundlerMinifier.BundlerBuildTask" task could not be loaded from the assembly C:\Users\namc\.nuget\packages\buildbundlerminifier\2.2.306\build\..\tools\BundlerMinifier.exe. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

### Expected behavior
Works in both VS and dotnet CLI

### PR DESCRIPTION
**Pull request by natemcmaster**
Updates BuildBundlerMinifier to run on both MSBuild.exe and dotnet-msbuild.
Update test project to VS2017.
Update BundlerMinifier.Core to build with csproj instead of project.json

Resolves #230

### CODE REVIEW

**Comment by natemcmaster** [comment]
cc @spboyer @danroth27 @madskristensen

**Comment by madskristensen** [comment]
The build failed. Do you know how to fix it?

**Comment by madskristensen** [comment]
...and thanks for helping out :)

**Comment by natemcmaster** [comment]
> The build failed. Do you know how to fix it?

Yeah. It appears AppVeyor has a build of CLI older than what I'm using. I'll add a few properties that are required in RC4 but will not be needed in RTM.

**Comment by natemcmaster** [comment]
🆙 📅  the build passes now. Btw, I'm not super familiar with the VSIX. I had to change a few minor things to make the ProjectReference work. What's a good way to verify I didn't break anything?

**Comment by madskristensen** [comment]
I can verify that

**Comment by natemcmaster** [comment]
Oops, there was one more thing that need to be fixed.

**Comment by natemcmaster** [comment]
There was another bug in dotnet pack RC4 that was fixed in the version I have. The build is leaving out NUglifier and Newtonsoft.Json from the BuildBundlerMinifier package.

**Comment by JoenSyncorder** [comment]
Visual Studio's TaskRunner tries to run "BundlerMinifier.exe", which no longer exists in v2.4.
The only new code in v2.4 that contains "BundlerMinifier.exe" happens to be in this issue. Could it be possible that this broke the Bundler & Minifier?

**Comment by madskristensen** [comment]
@JoenSyncorder I just released version 2.4.338 with a fix

**Comment by madskristensen** [comment]
@natemcmaster There was a bug since the BuildBundlerMinifier project no longer outputs a .exe but a .dll. I shell'ed out to that .exe from within VS at a particular scenario and that has now been broken. Is there a way to convert the project back to a console app without loosing the changes you've made? I gave it a try, but it seems not possible.

**Comment by natemcmaster** [comment]
>  Is there a way to convert the project back to a console app

Sorry, I didn't realize this assembly need to also function as a console application. Converting it back to a console app should be a matter of specifying `<OutputType Condition="'$(TargetFramework)' == 'net46'">Exe</OutputType>` and updating the targets file to use .exe instead of .dll. There may be some other consequences of the conversion. For example, Microsoft.Build* 15.1.0 dlls may not be in the GAC. 

It seems odd to build an assembly that is both a console app and an MSBuild task library. I'd recommend instead compiling a separate console application that doesn't have the MSBuild references.

**Pull request merged**
