### PR TITLE
Upgrade NUglify to 1.5.14

### LINKED ISSUE #469: Browsers don't support minified @supports-or
### Installed product versions
- Visual Studio: 2019 Enterprise 16.4.0
- Google Chrome 80.0.3987.106
- Mozilla Firefox 72.0.2
- This extension: 2.8.396

### Description
This extension minify
`@supports ((position:-webkit-sticky) or (position:sticky))`
to
`@supports ((position:-webkit-sticky)or(position:sticky))`
But browsers (I just tested on Chrome and Firefox) don't support this.

### PR DESCRIPTION
**Pull request by markhobson**
Should fix #469.

### CODE REVIEW

**Comment by madskristensen** [comment]
Thanks

**Comment by markhobson** [comment]
@madskristensen Thanks for the quick merge. Are there any plans for another release soon?

**Comment by madskristensen** [comment]
Not currently. Can you use the CI build of the VS extension for now?

**Comment by markhobson** [comment]
@madskristensen I'm after the BuildBundlerMinifier package - is the CI build of that available on any NuGet repository?

**Comment by madskristensen** [comment]
No, but i can make it available. give me 10 minutes

**Comment by madskristensen** [comment]
It's building. When complete, it will automatically push to NuGet. Then when NuGet is done indexing it will show up

**Comment by markhobson** [comment]
Amazing, thanks! Will it appear as a pre-release package?

**Comment by madskristensen** [comment]
No, regular release

**Comment by markhobson** [comment]
Works perfectly, thanks so much!

**Pull request merged**
