### PR TITLE
Add target frameworks for netcoreapp2.0

### PR DESCRIPTION
**Pull request by mlorbetske**

### CODE REVIEW

**Comment by madskristensen** [comment]
Build failed. Can't find .NET Core sdk 2.0 it says. I probably have to update the appveyor.yml file to pull the right version. Do you know it?

**Comment by mlorbetske** [comment]
`2.0.0-preview1-005977` I believe

**Comment by madskristensen** [comment]
It still wasn't able to resolve the 2.0 SDK though I changed the download in the appveyor.yml file. Any ideas?

**Comment by madskristensen** [comment]
Thanks

**Pull request merged**
