### PR TITLE
Support for Gzipped JS Bundles with no minification

### PR DESCRIPTION
**Pull request by ealsur**
When handling Bower libraries, they already come minified (mostly). So it's common to bundle them together and create a single JS file that holds them all so the Client makes just one request but we don't need that file to be minified further (there are cases where it breaks the file contents completely) but we do need it to be Gzipped.

With this change, it is now possible to create a JS Bundle with a minify setting of:

    {
    "enabled":false,
    "gzip":true,
    }

And the extension will bundle the files, not minify them, but Gzip them.

### CODE REVIEW

**Comment by madskristensen** [comment]
Great idea! It's a little difficult to see your changes with that many commits. Did you remember supporting .css and .html and not just .js gzipping?

**Comment by ealsur** [comment]
Sorry for the multiple commits, I try to use 1 commit per concept (the first 2 commits were a mistake, hence the revert). 

I just added support for JS, will do for CSS and HTML too then :)

**Comment by ealsur** [comment]
Done! Now it's supported on JS, CSS and HTML :)

Main commits are: https://github.com/madskristensen/BundlerMinifier/pull/148/commits/4f5e916a31423b519c55ded6ec34571ae097601c and https://github.com/madskristensen/BundlerMinifier/pull/148/commits/01cd9f932edaf150a085bc9abb749c27ffc0542b . The rest are Tests creation.

**Comment by madskristensen** [comment]
I had to revert this PR. It didn't work in a bunch of scenarios. We should rethink this some more

**Comment by ealsur** [comment]
Do you have a list of them Mads?  I can try them with tests and check them out.

**Comment by madskristensen** [comment]
I'm refactoring the code now to make it easier to see what's going on.

**Comment by ealsur** [comment]
Want me to give it another go now that it has been refactored? Do you have any kind of list of failed scenarios? I made sure to have all the tests running OK and even added one for the new scenario.

**Comment by madskristensen** [comment]
The issue was that it would generate a `.min.<ext>` file even if `"minify": false` in _bundleconfig.json_. 

What is the use case for this exactly?

**Comment by ealsur** [comment]
I thought about the `.min.<ext>` too, and on my first version, that file was not generated, but then I found out that the internal functions that detected if the file content was changed depended on it.

To detect a content change (and fire the code tree that called the Gzip function) it would take the original file, minify it, compare the results with the existing file and if it was indeed changed, it would keep going.

Without generating the `.min.<ext>` file, it wasn't possible to know if the input changed from a previous state.

If you come from a Gulp+Bower scenario on ASP.NET Core, you are writing your own JS code and using Bower to pull libraries. The Bower libraries always come minified and sometimes their minification is not a standard one, it's tailored in such a way that it differs from one generated by a default minification mechanism (for example, some work with local name replacement, some don't, some can be [mangled](https://github.com/gruntjs/grunt-contrib-uglify#mangle), some don't). 

If you pick the un-minified versions and try to bundle them together and minify the bundle, it has a high chance of breaking the code, and depends entirely on the good coding practices that each Library author followed (or did not).

For example, I tried to bundle jQuery+Angular+Bootstrap+Some_Angular_modules and the minification mechanism would hoist variable declarations and mix the order (Angular modules are very dependant on it) of the code and the final product would have Syntax errors or dependency problems on declared modules (I can create a repro repo if needed).

For that reason, with Gulp, you can do something like:

    gulp.task('bundleLayout', function () {
        return gulp.src([
            lib + '/js/layout/jquery.min.js',
            lib + '/js/layout/angular.min.js',
            lib + '/js/layout/ui-bootstrap-tpls.min.js',
            lib + '/js/layout/ng-file-upload.min.js',
            lib + '/js/layout/ng-infinite-scroll.min.js',
            lib + '/js/layout/angular-ui-router.min.js',
            lib + '/js/layout/angular-sanitize.min.js'
            ])
            .pipe(concat('layout.js'))
            .pipe(gzip({ gzipOptions: { level: 5 } }))
            .pipe(gulp.dest(lib + '/js/bundle/'));
    });

But I was unable to achieve that with BundleMinifier. That was the reason behind my PR.

I would love to eliminate the `.min.<ext>` generation on the scenario, but I don't know how to track file content changes then. Gulp has a [watch](https://www.npmjs.com/package/gulp-watch) module that fires only when the file changes, maybe something can be taken from there.

**Comment by madskristensen** [comment]
Thanks for clarifying. That makes sense to me now.

I've refactored the code in such a way that it would be fairly simple to implement GZipping when minification is set to false. Please feel free to send a new PR.

Test cases:
- outputFileName ending in _.min.[ext]_
- outputFileName **not** ending in _.min.[ext]_
- inputFiles containing only a single file
- inputFiles containing multiple files

**Comment by ealsur** [comment]
Will do, thanks Mads!

**Pull request merged**
