### PR TITLE
Update NUglify to 1.5.12

### PR DESCRIPTION
**Pull request by Tonher31**
Update NuGet package NUglify to version 1.5.12 : resolve async and await errors #311, #379.

### CODE REVIEW

**Comment by madskristensen** [comment]
Thanks

**Comment by SteinTheRuler** [comment]
is there a step by step guide for doing this? by the files it seems I have to download source (for some reason). why is this still an issue? I installed the extension for less than a month ago and it looks like it still uses the old version. is there a way to update version without editing source code?

**Comment by maurocordovaf** [comment]
I'm facing the same issue, any thing we can do to fix this?

**Comment by alejandre** [comment]
I have the same error

**Pull request merged**
