### PR TITLE
Support .NET Core 3.0 in global tool

### PR DESCRIPTION
**Pull request by martincostello**
Add `netcoreapp3.0` as a supported target framework.

Relates to #442.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Alternative which compile what was working before: https://github.com/madskristensen/BundlerMinifier/pull/444

**Comment by martincostello** [comment]
I thought #444 incorporated this change, but it doesn’t.

I’ll rebase it later, then can this be merged too @rockstardev so that .NET Core 3.0 is supported for the global tool too?

**Comment by martincostello** [comment]
Rebased - can this be merged and released please?

**Comment by NicolasDorier** [comment]
@martincostello I don't think this is necessary. I checked those two assemblies does not reference any libraries that got deleted in netcoreapp and which could conflict.

**Comment by NicolasDorier** [comment]
Oh actually this is a dotnet global tool. So I may be wrong.
This confused be as TargetFramework .netstandard for a executable should not happen in theory.

**Comment by martincostello** [comment]
It is necessary - if the .NET Core 2.2 runtime is not installed and only the 3.0 runtime, the global tool will not run. I'm currently having to install 2.2 and 3.0 in CI environments so that I can use the tool.

**Comment by NicolasDorier** [comment]
@martincostello yes I think you are right, this would explain why it worked on my machine (I have 2.2)

**Comment by NicolasDorier** [comment]
Though I don't think you need for BundlerMinifier.csproj

**Comment by martincostello** [comment]
I updated both on the basis they already had `netcoreapp1.01 and `netcoreapp2.0`.

**Comment by rockstardev** [comment]
@madskristensen looked now... yeah, definitely looks like we need this also. Let me know if you want anything else added before I publish this.

Quick related question - will we be able to have 3.10.xxxx and 3.11.xxxx versions? I definitely plan to slow down on pushing updates, but just in case we need it ;)

**Comment by NicolasDorier** [comment]
@rockstardev no, there will be only a netcoreapp3.1 in one month. Next runtime will be 5.0 in a year or so.

**Comment by rockstardev** [comment]
@NicolasDorier I'm asking for BundlerMinifier version ;)

**Comment by rockstardev** [comment]
Just quick notice - adding this and installing .NET Core 3.0 has completely crashed my Visual Studio 2017 setup. I'm not sure if we are still maintaining compatibility with older Visual Studio editions... in case someone else runs into problems and sees all this, please open new issue and reference this post.

**Comment by martincostello** [comment]
Had an issue on update, see #450.

**Comment by rockstardev** [comment]
Just to confirm that installing Visual Studio 2019 and then building BundlerMinifier with it works flawlessly.

As for your problem @martincostello - I've responded directly on the issue.

**Pull request merged**
