### PR TITLE
minify bundles only when they change

### PR DESCRIPTION
**Pull request by valeriob**
Minification is very slow on a decent project (it takes 30+ seconds with 20+ bundles) on build because it runs even if files are not changed

### CODE REVIEW

**Comment by madskristensen** [comment]
@mlorbetske What do you think about this?

**Comment by mlorbetske** [comment]
It looks like this only checks for changes in the output file, shouldn't we check the source files for changes instead? In order to do this, we'd also need to know whether the configuration that produced the bundle has changed between runs, so we'd need a secondary artifact to track that. Agree with the idea here though, bundles should only be recreated if there have been changes to the sources or configuration.

**Comment by valeriob** [comment]
Thanks @mlorbetske, from what i could understand Bundle is a mutable structure, so it's a bit hard to reason about it. 
I think that  BundleHandler.ProcessBundle(baseFolder, bundle); is assigning the value to the Bundle.Output property that infact is the actual concatenation of files (is the actual input of the process).

**Comment by valeriob** [comment]
Hi,
the BundlerMinifier released keeps slowing up builds quite a lot. I do not understand how ppl are using it, is crazy to wait minutes for a build, it makes me wonder that not many ppl use it :( This pull request solves the issue and is many months old :D

**Comment by valeriob** [comment]
Hi,
BundlerMinifier last release is still very very slow because it keeps updating always all bundles, i do not understand how are people using it day by day. Pls consider merging this pull request, you are going to do a favor to a lot of ppl unaware about the causes of the slow builds...

**Comment by valeriob** [comment]
Do you think you can merge this in the next release ?
We have being using this branch for months now, the master one impact build time way to much when you have more than 5/6 bundles

**Comment by madskristensen** [comment]
I don't understand how this helps if it checks for changes to output files. It needs to look at the input files. Can you help me understand?

**Comment by valeriob** [comment]
MinifiedBundle=Minify(Bundle(items));
if any items changes => bundle changes => minified changes.
The solution has 20 bundles, since minifying is very very slow, and i repeat it's run on the same UI process it blocks Vs GUI during this process.

With Master Version on hot run (second run where no file has being changed) it takes 26 seconds
image

With my patch 0.3s
image

**Comment by hierro1981** [comment]
We have facing the same problem of slow build due to bundles time, if this patch will fix it why it is still pending to be merged?

**Comment by valeriob** [comment]
Guys, i think that a lot of time is passed, can you pls consider this pull request ?
We have to wait way too much to minify stuff that did not change !!

**Comment by valeriob** [comment]
pretty pls...

image

**Comment by rockstardev** [comment]
We have finally addressed this with #438 & #439 ... let us know if it works well for you and sorry for the delay!

**Pull request closed without merging**
